### ISSUE TITLE
🐛 使用 Node.js 的 child_process 执行时 os.get_terminal_size 报错

### ISSUE THREAD

**Issue by DIYgod** [SigureMo/bilili#103]
## 调用方式

```js
const { exec } = require('child_process');
exec(command, (err, stdout, stderr) => {});
```

## 环境信息

错报信息

```
Traceback (most recent call last):
  File "/usr/local/bin/bilili", line 5, in <module>
    from bilili.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/bilili/__main__.py", line 19, in <module>
    from .utils.console.ui import ColorString, Line, LineList, ProgressBar, String, View
  File "/usr/local/lib/python3.9/site-packages/bilili/utils/console/ui.py", line 204, in <module>
    class ProgressBar(Component):
  File "/usr/local/lib/python3.9/site-packages/bilili/utils/console/ui.py", line 205, in ProgressBar
    def __init__(self, symbols: Union[str, List[str]] = "░▏▎▍▌▋▊▉█", width: int = View.get_width()):
  File "/usr/local/lib/python3.9/site-packages/bilili/utils/console/ui.py", line 50, in get_width
    width = os.get_terminal_size().columns
OSError: [Errno 102] Operation not supported on socket
```

报错位置

https://github.com/SigureMo/bilili/blob/main/bilili/utils/console/ui.py#L50

## 问题简述

在我的一个 Node.js 小项目 [download-webhook](https://github.com/DIYgod/download-webhook) 使用时遇到的问题，从 v1.4.7 更新至 v1.4.8 后出现

**Comment by SigureMo** [comment]
呀是DIY～我这就去修(●• ̀ω•́ )✧

**Comment by SigureMo** [comment]
修好啦（应该是这样的）～升级 1.4.9 就好啦(๑>؂<๑）

**Comment by DIYgod** [comment]
哇谢谢 Nyakku！！
