### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by Yuelioi** [SigureMo/bilili#105]
```
Traceback (most recent call last):
  File "c:\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\py37\Scripts\bilili.exe\__main__.py", line 4, in <module>
  File "c:\py37\lib\site-packages\bilili\__main__.py", line 144
    if (avid_match := regex.acg_video.av.origin.match(args.url)) or \
                   ^
SyntaxError: invalid syntax
```

1. 环境信息

-  OS： Windows
-  Python： 3.7.9
-  bilili： bilili 版本号
-  Others： 其它信息

2. 问题简述

-  python环境变量没问题（可以CMD输入python）
-  也可以CMD里import bilili
-  但是直接使用CMD直接输入 bilili提示语法错误SyntaxError: invalid syntax

![QQ截图20210712155817](https://user-images.githubusercontent.com/46314093/125251590-12e41080-e32a-11eb-9e6b-12f03836e77e.png)

**Comment by SigureMo** [comment]
只支持 Python3.8+ 啊
