### ISSUE TITLE
Does not work with Transocks VPN🐛 

### ISSUE THREAD

**Issue by jtalsby** [SigureMo/bilili#121]
C:\Users\Jay>bilili https://www.bilibili.com/bangumi/play/ss38876 -p 1
[30m[42m INFO [0m 未提供 SESSDATA，无法下载会员专享剧集的喔～
干物妹！小埋 中配版
全 12 话
已选择第 1 话
Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000024F5BA2F460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xy182x119x167x227xy.mcdn.bilivideo.cn', port=4483): Max retries exceeded with url: /upgcxcode/87/82/371198287/371198287_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1640329260&gen=playurlv2&os=mcdn&oi=1033807754&trid=000055c6d6991bbc4013b73e747bb7c2e1bdp&platform=pc&upsig=6ae1e1ca8c37b8289b74e7af39bcf450&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mcdnid=2001618&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=94145&logo=A0000002 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024F5BA2F460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jay\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python39\Scripts\bilili.exe\__main__.py", line 7, in <module>
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\__main__.py", line 276, in main
    for playinfo in get_playurl(container, config["quality"], config["audio_quality"]):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\parser\bangumi.py", line 30, in get_playurl
    play_list = get_bangumi_playurl(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\api\utils.py", line 20, in connect_n_times
    return connect_once(*args, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\api\bangumi.py", line 164, in get_bangumi_playurl
    "size": touch_url(video["base_url"], spider)[0],
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\utils\base.py", line 64, in touch_url
    res = method(url, headers={"Range": "bytes=0-4"})
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 577, in head
    return self.request('HEAD', url, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xy182x119x167x227xy.mcdn.bilivideo.cn', port=4483): Max retries exceeded with url: /upgcxcode/87/82/371198287/371198287_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1640329260&gen=playurlv2&os=mcdn&oi=1033807754&trid=000055c6d6991bbc4013b73e747bb7c2e1bdp&platform=pc&upsig=6ae1e1ca8c37b8289b74e7af39bcf450&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mcdnid=2001618&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=94145&logo=A0000002 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024F5BA2F460>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

C:\Users\Jay>bilili https://www.bilibili.com/bangumi/play/ss38876 -p 1 --debug
[30m[42m INFO [0m 未提供 SESSDATA，无法下载会员专享剧集的喔～
干物妹！小埋 中配版
全 12 话
已选择第 1 话
Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023D60425AF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xy221x15x253x114xy.mcdn.bilivideo.cn', port=4483): Max retries exceeded with url: /upgcxcode/87/82/371198287/371198287_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1640329349&gen=playurlv2&os=mcdn&oi=1033807754&trid=00007cdec0c97dc34728a40430876a6b3419p&platform=pc&upsig=e85a405ae2f9da58722906f084fc226e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mcdnid=8000249&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=94145&logo=A0000080 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023D60425AF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jay\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jay\AppData\Local\Programs\Python\Python39\Scripts\bilili.exe\__main__.py", line 7, in <module>
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\__main__.py", line 276, in main
    for playinfo in get_playurl(container, config["quality"], config["audio_quality"]):
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\parser\bangumi.py", line 30, in get_playurl
    play_list = get_bangumi_playurl(
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\api\utils.py", line 20, in connect_n_times
    return connect_once(*args, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\api\bangumi.py", line 164, in get_bangumi_playurl
    "size": touch_url(video["base_url"], spider)[0],
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\bilili\utils\base.py", line 64, in touch_url
    res = method(url, headers={"Range": "bytes=0-4"})
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 577, in head
    return self.request('HEAD', url, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\jay\appdata\local\programs\python\python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xy221x15x253x114xy.mcdn.bilivideo.cn', port=4483): Max retries exceeded with url: /upgcxcode/87/82/371198287/371198287_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1640329349&gen=playurlv2&os=mcdn&oi=1033807754&trid=00007cdec0c97dc34728a40430876a6b3419p&platform=pc&upsig=e85a405ae2f9da58722906f084fc226e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mcdnid=8000249&mid=0&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=94145&logo=A0000080 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023D60425AF0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

**Comment by jtalsby** [comment]
Just had to set the 代理DNS to true in the Transocks settings and set the 模式 to 电脑全局模式 instead of 智能模式.
