### ISSUE TITLE
🐛 大会员状态下无法下载会员番 & 编码问题

### ISSUE THREAD

**Issue by abc1763613206** [SigureMo/bilili#82]
## 调用方式

```bash
$ bilili -c $SESSDATA https://www.bilibili.com/bangumi/play/ss24588 -p 2
工作细胞
全 14 话
已选择第 2 话
[warn] 第2话 擦伤 无法下载，原因：「-10403」 大会员专享限制
✖ 第2话 擦伤 「」
以上标 ✖ 为需要进行下载的视频，是否立刻进行下载？[Y/n]
```
顺便一提，使用 `Y` 回复后，整个脚本就卡掉无响应了（

## 环境信息

-  OS： `WSL1 Ubuntu 20.04`
-  Python： `Python 3.8.5`
-  bilili： `1.3.7`
-  如果是显示相关问题
   -  Shell：`cmd/bash`
   -  Terminal：`cmd/Git Bash`

## 问题简述

1. 带着大会员的 SESSDATA 下无法解析会员番，已经确定 SESSDATA 没有其他问题（下载普通视频时能解析出高码率来）。
2. 界面交互有问题，上文中当检测到不能下载时应当进行终止，而不应当在用户 `Y/-y` 后继续下载，最后无限刷新使界面卡住。

## 预期行为

1. 正常解析并下载。
2. 优化界面交互，不能下载时直接终止。

## 额外信息

卡顿界面强行 <kbd>Ctrl</kbd> + <kbd>C</kbd> 时的输出：
```
Traceback (most recent call last):
  File "/usr/local/bin/bilili", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/bilili/__main__.py", line 441, in main
    time.sleep(max(1 / refresh_rate - (time.time() - now_t), 0.01))
KeyboardInterrupt
```

顺便一提，符号「✖」有些花活，在大部分常规平台均无法正常显示，建议替换成常规Unicode符号（如`-`/`+`）。
该符号还会导致一些终端的交互锅掉，比如说如下是 `Git Bash` 的显示：
```bash
abc17@Jerry MINGW64 /h
$ bilili -c [SECRET] https://www.bilibili.com/bangumi/play/ss24588 -p 2
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\bilili.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\bilili\__main__.py", line 264, in main
    print("{} {}".format(symbol, str(container)))
UnicodeEncodeError: 'gbk' codec can't encode character '\u2716' in position 0: illegal multibyte sequence
工作细胞
全 14 话
已选择第 2 话
[warn] 第2话 擦伤 无法下载，原因：「-10403」 大会员专享限制
```
编码处理不好时，在使用 subprocess 简易交互时也会吐类似信息使交互失败，（我现在已经被迫用写入 bat 再执行的屑 workaround 了）

~~🍻 𝓫𝓲𝓵𝓲𝓵𝓲 多半情况下也无法显示，暂且不提。~~

## 是否愿意为此贡献代码
扫了一眼，倒是没看懂 API 实现。

**Comment by SigureMo** [comment]
``` bash
$ bilili -c $SESSDATA https://www.bilibili.com/bangumi/play/ss24588 -p 2
```

我这里是完全可以下载的……
