### ISSUE TITLE
🐛 v1.4.4 发生 ModuleNotFoundError

### ISSUE THREAD

**Issue by cart88** [SigureMo/bilili#94]
## 调用方式
```
[root@localhost ~]# pip3.8 install bilili==1.4.4
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting bilili==1.4.4
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/cf/ab19c6f7c98cf88829fe83bda1e8c54fe8a10afc4857c77b8c34a4787c73/bilili-1.4.4-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (from bilili==1.4.4) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests->bilili==1.4.4) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests->bilili==1.4.4) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests->bilili==1.4.4) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests->bilili==1.4.4) (2020.12.5)
Installing collected packages: bilili
Successfully installed bilili-1.4.4
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[root@localhost ~]# bilili
Traceback (most recent call last):
  File "/usr/local/bin/bilili", line 5, in <module>
    from bilili.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/bilili/__main__.py", line 9, in <module>
    from .api.danmaku import get_danmaku
  File "/usr/local/lib/python3.8/site-packages/bilili/api/danmaku.py", line 4, in <module>
    from ..tools import spider
  File "/usr/local/lib/python3.8/site-packages/bilili/tools.py", line 3, in <module>
    from .handlers.status import DownloaderStatus
  File "/usr/local/lib/python3.8/site-packages/bilili/handlers/status.py", line 3, in <module>
    from ..utils.console.logger import Logger
  File "/usr/local/lib/python3.8/site-packages/bilili/utils/console/logger.py", line 3, in <module>
    from ..functiontools.singleton import Singleton
ModuleNotFoundError: No module named 'bilili.utils.functiontools'
```
## 环境信息

-  OS： centos7 2009 minimal
-  Python： 3.8.7 3.8.8 3.8.9
-  bilili： bilili 1.4.4
-  如果是显示相关问题
   -  Shell：bash

**Comment by SigureMo** [comment]
刚刚我重新 release 了下，升级一下再试试：

```
pip install --upgrade bilili
```

**Comment by cart88** [comment]
问题解决了.ok，谢谢
